apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: black-sea-admin-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    nginx.ingress.kubernetes.io/auth-url: "http://oauth2-proxy.auth-proxy.svc.cluster.local/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://oauth2-proxy.cluster.tennander.se/oauth2/start?rd=$scheme://$host$escaped_request_uri"
    nginx.ingress.kubernetes.io/auth-response-headers: "X-Auth-Request-User,X-Auth-Request-Email,X-Auth-Request-Groups"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - world.black-sea.tennander.se
      secretName: black-sea-tls
  rules:
    - host: world.black-sea.tennander.se
      http:
        paths:
          - path: /admin
            pathType: Prefix
            backend:
              service:
                name: black-sea-service
                port:
                  number: 8080
